husky pre-commit: lint changed files and stage (lint) changes; test / lint only when needed

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,6 +1,19 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npx eslint --cache --fix src
-echo "running yarn test..."
-yarn test
+fileList=$(git diff --diff-filter=d --cached --name-only | grep src/ | tr '\n' ' ' | xargs)
+lintFileList=$(echo $fileList | tr ' ' '\n' | grep -E '\.(ts|js)$' | tr '\n' ' ' | xargs)
+
+# test for errors
+if [ "$fileList" != "" ];
+then
+yarn test;
+fi;
+
+# lint
+if [ "$lintFileList" != "" ];
+then
+yarn eslint --fix $lintFileList || echo "WARNING: eslint failed to run";
+yarn prettier --write $lintFileList || echo "WARNING: prettier failed to run";
+git add $lintFileList;
+fi;
